### ISSUE TITLE
[3.0] Phar build script

### ISSUE THREAD

**Issue by gordalina** [elfet/deployer#137]
I'm using [this build script](https://github.com/gordalina/cachetool/blob/master/bin/bump-version.sh) which was based off [this article](http://moquet.net/blog/distributing-php-cli/)

Also I added the [self update command](https://github.com/gordalina/cachetool/blob/master/src/CacheTool/Command/SelfUpdateCommand.php)

**Comment by elfet** [comment]
But what is wrong with current build script?

**Comment by elfet** [comment]
I'll create new site with autoupdate phar script. It will be triggered automatically when new commits will be pushed or PR megred.

So it will be `dev-master` phar version available on site :)

**Comment by gordalina** [comment]
As far as I can see, it does not update everything automatically: create phar, add it to manifest, commit, publish a new tag and push everything to GH.
Also, you had this on your 3.0 task list: https://github.com/elfet/deployer/blob/master/README.md

**Comment by gordalina** [comment]
awesome

**Comment by elfet** [comment]
So i close this issue? 

@gordalina can you work on WordPress and/or Zend Framework recipes? :trophy:

**Comment by gordalina** [comment]
i'm not really experienced in wordpress, and last time I deployed a zend app was 3 years ago.
I don't think i'm the best person to do it.

btw, you have in the tasklist a refactor of common/symfony recipes, what are you planning to do?

**Comment by elfet** [comment]
Yes, i'm already refactored Symfony recipe (not published yet), not writing tests for what recipe.
