### ISSUE TITLE
Deployment to localhost without ssh overhead

### ISSUE THREAD

**Issue by mabrahamde** [elfet/deployer#138]
Inside deployer there is functionality for local deployment without ssh overhead. 

I like the idea of executing deployer directly on the server(s). In this case you do not need to connect via ssh. You can execute all commands directly. 

Inside the master branch there is a function localServer(). However it is not in the 2.x release. Building the phar from source doesn't result in a functional version.

Clould you provide a functional phar file for local deployments?

**Comment by elfet** [comment]
Yes, of course where will be phar version of Deployer available to download from site (in progress). 

Now you can clone master branch and run `php bin/build` command to build phar archive yourself.

**Comment by mabrahamde** [comment]
the api has changed somehow. how do you set server paths now? how do you configure stages?

**Comment by elfet** [comment]
New docs in process...

Example on server configuration:
```php
server(...)
    ->env('deploy_path', '/home/web');
```

Stages:
```php
serverGroup('pre', ['test', 'dev', 'production]);
```

**Comment by mabrahamde** [comment]
thanks
